### ISSUE TITLE
Main project page information has typo (or there's an issue)

### ISSUE THREAD

**Issue by freeform-sg** [backdrop-contrib/view_unpublished#1]
The following text is the opposite of what you need to do for it to work:

> If using view_unpublished with Views, use the "Published or admin" filter, NOT "published = yes". Views will then respect your custom permissions.

Permission "Published or admin" should be dropped, and published = yes or no used instead, otherwise content overview page will not return any results for unpublished content.

**Comment by bugfolder** [comment]
No, I think the instructions are correct. Here's a specific scenario:

* Create a Page titled "Unpublished Page," leave it unpublished.
* Create a Post titled "Unpublished Post," leave it unpublished.
* Create a Role, "View unpublished".
* Give it these permissions 
  * "Access the content overview page"
  * "Use the administration pages"
  * "View the administration theme"
  * "Page: View any unpublished content"
* Create a user, "Tester", and give it the role "View unpublished."

Now, if you login as Tester and go to admin/content, you will see "Unpublished Page" but not "Unpublished Post," so the content overview page is working properly according to the permissions you gave in View Unpublished.

Next, let's try out a View.

* Create a View that displays nodes of all types with path `all-content`.
* The default filter will be "Content: Published". Save.

The result is that neither unpublished node will be shown to Tester.

Go back and edit the View.

* Remove the "Content: Published" filter.
* Add the "Content: Published or admin" filter.
* Save.

The result is that "Unpublished Page" will be shown to Tester, but not "Unpublished Post." So, basically, what's shown in this View will mirror what is shown on the content overview page.

And that is what the instructions are saying.

Hope this helps clarify things.

If you're seeing something different, please give a detailed description of how to reproduce the puzzling behavior (similar to the above) and I'll look into it.

**Comment by bugfolder** [comment]
Closed due to no further response.
